name: Build and testing the project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    strategy:
      matrix:
        compiler: [gcc, clang]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install tools with ${{ matrix.compiler }}
        shell: bash
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y ${{ matrix.compiler }} cmake
          echo CC=${{ matrix.compiler }} >> $GITHUB_ENV

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build build --config Release

      - name: Run tests
        working-directory: ./build
        run: ctest --output-on-failure