name: Build and testing the project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  msvc-gen: 'Visual Studio 18 2026'

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest

    strategy:
      fail-fast: false

      matrix:
        os:
          - windows
          - ubuntu
          - macos
        compiler:
          - gcc
          - llvm
        is-shared:
          - OFF
          - ON
        build-type:
          - Release
          - Debug
        generator:
          - "Unix Makefiles"

        include:
          - os: windows
            compiler: msvc
            is-shared: OFF
            build-type: Release
            generator: ${{ env.msvc-gen }}

          - os: windows
            compiler: msvc
            is-shared: ON
            build-type: Release
            generator: ${{ env.msvc-gen }}

          - os: windows
            compiler: msvc
            is-shared: OFF
            build-type: Debug
            generator: ${{ env.msvc-gen }}

          - os: windows
            compiler: msvc
            is-shared: ON
            build-type: Debug
            generator: ${{ env.msvc-gen }}

    steps:
      - uses: actions/checkout@v6

      - name: Setup C compiler
        uses: aminya/setup-cpp@v1
        with:
          compiler:  ${{ matrix.compiler }}
          vcvarsall: ${{ matrix.compiler == 'msvc' }}
          make:      ${{ matrix.compiler != 'msvc' }}

          cmake: true

      - name: Enable variables for MSVC
        if: ${{ matrix.compiler == 'msvc' }}
        working-directory: "C:\\Program Files (x86)\\Microsoft Visual Studio\\18\\BuildTools\\VS\\Auxiliary\\Build"
        run: |
          .\\vcvarsall.bat

      - name: Configure CMake
        run: >
          cmake -S . -B build -G "${{ matrix.generator }}"
          -DCMAKE_BUILD_TYPE:STRING=${{ matrix.build-type }}
          -DBUILD_SHARED_LIBS:BOOL=${{ matrix.is-shared }}

      - name: Build project
        run: |
          cmake --build build --config ${{ matrix.build-type }}

      - name: Run tests
        working-directory: ./build
        run: |
          ctest --output-on-failure -C ${{ matrix.build-type }}